name: Update Election Data

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install curl_cffi beautifulsoup4

      - name: Run scraper
        run: python fetch_results.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add results.json results.csv
          git commit -m "Update results $(date -u)" || echo "No changes"
          git push
